/* eslint-disable no-undef */
const fs = require('fs');
const path = require('path');
const http = require('http');

// Default to 5000 if not set, matching common Hostinger/local config
const PORT = process.env.PORT || 5000;
const SERVICE_ACCOUNT_FILENAME = 'service-account.json';
const SERVICE_ACCOUNT_PATH = path.join(process.cwd(), SERVICE_ACCOUNT_FILENAME);

function startFallbackServer(message) {
    console.error('--- STARTUP FAILURE ---');
    console.error(message);
    console.error('-----------------------');

    const server = http.createServer((req, res) => {
        // Serve with 503 status so search engines don't index this, but user sees content
        res.writeHead(503, { 'Content-Type': 'text/html; charset=utf-8' });
        res.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>Startup Error - EstateManager</title>
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <style>
            body { font-family: -apple-system, system-ui, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; padding: 2rem; max-width: 800px; margin: 0 auto; background-color: #f9fafb; color: #1f2937; }
            .container { background: white; padding: 2rem; border-radius: 0.5rem; box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); }
            h1 { color: #dc2626; font-size: 1.5rem; margin-top: 0; }
            .error-box { background-color: #fef2f2; border-left: 4px solid #dc2626; padding: 1rem; margin: 1.5rem 0; overflow-x: auto; }
            pre { margin: 0; white-space: pre-wrap; font-size: 0.875rem; color: #991b1b; }
            .solution { margin-top: 1.5rem; border-top: 1px solid #e5e7eb; padding-top: 1rem; }
            code { background: #f3f4f6; padding: 0.2rem 0.4rem; border-radius: 0.25rem; font-family: monospace; }
          </style>
        </head>
        <body>
          <div class="container">
            <h1>Application Failed to Start</h1>
            <p>The application encountered a critical error during startup and could not launch.</p>
            
            <div class="error-box">
              <strong>Error Details:</strong>
              <pre>${message}</pre>
            </div>

            <div class="solution">
              <h3>Troubleshooting:</h3>
              ${message.includes('service-account.json') ?
                `<p><strong>Issue: Use of missing Firebase Credentials.</strong><br/>The file <code>service-account.json</code> is missing from the server root.</p>
                 <p><strong>Fix:</strong> Upload your local <code>service-account.json</code> to the <code>public_html</code> folder via the Hostinger File Manager.</p>` :
                `<p>Check the server logs for more details.</p>`
            }
            </div>
            <p style="text-align: center; margin-top: 2rem; color: #6b7280; font-size: 0.875rem;">Generated by Hostinger Wrapper Script</p>
          </div>
        </body>
      </html>
    `);
        res.end();
    });

    server.listen(PORT, '0.0.0.0', () => {
        console.log(`Fallback error server running on port ${PORT}`);
    });
}

// 1. Check strict requirements that cause immediate process.exit in legacy code
if (!fs.existsSync(SERVICE_ACCOUNT_PATH)) {
    startFallbackServer(`CRITICAL: ${SERVICE_ACCOUNT_FILENAME} is MISSING.\nPath checked: ${SERVICE_ACCOUNT_PATH}\n\nThis file is required for Firebase initialization.`);
} else {
    // 2. Try to start the real app
    try {
        console.log('Wrapper: Checks passed. Importing dist/index.cjs...');
        require('./dist/index.cjs');
    } catch (err) {
        if (err.message && err.message.includes('Cannot find module')) {
            // This might happen if dist isn't built
            startFallbackServer(`Build Artifacts Missing. Could not find './dist/index.cjs'.\nDid you run 'npm run build'?\n\nFull Error: ${err.message}`);
        } else {
            startFallbackServer(`Runtime Exception during startup:\n${err.stack}`);
        }
    }
}
